#!/bin/sh

./azure-container-instance_by_project.sh Codec 18 VERIFY
./azure-container-instance_by_project.sh Collections 25 VERIFY
./azure-container-instance_by_project.sh Compress 47 VERIFY
./azure-container-instance_by_project.sh Csv 1 VERIFY
./azure-container-instance_by_project.sh Gson 18 VERIFY
./azure-container-instance_by_project.sh JacksonDatabind 80 VERIFY
./azure-container-instance_by_project.sh JacksonXml 2 VERIFY
./azure-container-instance_by_project.sh Jsoup 93 VERIFY
./azure-container-instance_by_project.sh Lang 1 VERIFY
./azure-container-instance_by_project.sh Math 104 VERIFY
./azure-container-instance_by_project.sh Time 1 VERIFY
./azure-container-instance_by_project.sh Codec 18 JAGUAR
./azure-container-instance_by_project.sh Collections 25 JAGUAR
./azure-container-instance_by_project.sh Compress 47 JAGUAR
./azure-container-instance_by_project.sh Csv 1 JAGUAR
./azure-container-instance_by_project.sh Gson 18 JAGUAR
./azure-container-instance_by_project.sh JacksonDatabind 80 JAGUAR
./azure-container-instance_by_project.sh JacksonXml 2 JAGUAR
./azure-container-instance_by_project.sh Jsoup 93 JAGUAR
./azure-container-instance_by_project.sh Lang 1 JAGUAR
./azure-container-instance_by_project.sh Math 104 JAGUAR
./azure-container-instance_by_project.sh Time 1 JAGUAR
./azure-container-instance_by_project.sh Codec 18 FLACOCO
./azure-container-instance_by_project.sh Collections 25 FLACOCO
./azure-container-instance_by_project.sh Compress 47 FLACOCO
./azure-container-instance_by_project.sh Csv 1 FLACOCO
./azure-container-instance_by_project.sh Gson 18 FLACOCO
./azure-container-instance_by_project.sh JacksonDatabind 80 FLACOCO
./azure-container-instance_by_project.sh JacksonXml 2 FLACOCO
./azure-container-instance_by_project.sh Jsoup 93 FLACOCO
./azure-container-instance_by_project.sh Lang 1 FLACOCO
./azure-container-instance_by_project.sh Math 104 FLACOCO
./azure-container-instance_by_project.sh Time 1 FLACOCO
./azure-container-instance_by_project.sh Codec 18 GZOLTARCLI
./azure-container-instance_by_project.sh Collections 25 GZOLTARCLI
./azure-container-instance_by_project.sh Compress 47 GZOLTARCLI
./azure-container-instance_by_project.sh Csv 1 GZOLTARCLI
./azure-container-instance_by_project.sh Gson 18 GZOLTARCLI
./azure-container-instance_by_project.sh JacksonDatabind 80 GZOLTARCLI
./azure-container-instance_by_project.sh JacksonXml 2 GZOLTARCLI
./azure-container-instance_by_project.sh Jsoup 93 GZOLTARCLI
./azure-container-instance_by_project.sh Lang 1 GZOLTARCLI
./azure-container-instance_by_project.sh Math 104 GZOLTARCLI
./azure-container-instance_by_project.sh Time 1 GZOLTARCLI
./azure-container-instance_by_project.sh Codec 18 JAGUAR2
./azure-container-instance_by_project.sh Collections 25 JAGUAR2
./azure-container-instance_by_project.sh Compress 47 JAGUAR2
./azure-container-instance_by_project.sh Csv 1 JAGUAR2
./azure-container-instance_by_project.sh Gson 18 JAGUAR2
./azure-container-instance_by_project.sh JacksonDatabind 80 JAGUAR2
./azure-container-instance_by_project.sh JacksonXml 2 JAGUAR2
./azure-container-instance_by_project.sh Jsoup 93 JAGUAR2
./azure-container-instance_by_project.sh Lang 1 JAGUAR2
./azure-container-instance_by_project.sh Math 104 JAGUAR2
./azure-container-instance_by_project.sh Time 1 JAGUAR2
./azure-container-instance_by_project.sh Codec 18 GZOLTARMAVEN
./azure-container-instance_by_project.sh Collections 25 GZOLTARMAVEN
./azure-container-instance_by_project.sh Compress 47 GZOLTARMAVEN
./azure-container-instance_by_project.sh Csv 1 GZOLTARMAVEN
./azure-container-instance_by_project.sh Gson 18 GZOLTARMAVEN
./azure-container-instance_by_project.sh JacksonDatabind 80 GZOLTARMAVEN
./azure-container-instance_by_project.sh JacksonXml 2 GZOLTARMAVEN
./azure-container-instance_by_project.sh Jsoup 93 GZOLTARMAVEN
./azure-container-instance_by_project.sh Lang 1 GZOLTARMAVEN
./azure-container-instance_by_project.sh Math 104 GZOLTARMAVEN
./azure-container-instance_by_project.sh Time 1 GZOLTARMAVEN
